### PR TITLE
Fix CI typecheck failure due to changed cassettes

### PR DESCRIPTION
**Pull request by shrik450**
The CI typecheck script fails on any differences in the working directory, and is therefore sensitive to minor changes in the cassettes. We should not be failing of diffs in the cassettes for three reasons:

1. The changes are usually minor, such as in the headers, and we shouldn't be sensitive to those;
2. Changes that affect the logic will be tested in the API or Utils tests; and
3. Changes in the API responses that affect the attribute types will be highlighted by diffing the API object file alone.

Therefore, this commit:

1. Completely disables vcr.py in the scheduled tests so that the cassettes are not touched at all; and
2. Diffs only the apiobject.py file to check if the types have changed.

### CODE REVIEW

**Review by McRaeAlex — COMMENTED** [review]
My understanding is changing the flag on pytest makes this not change the recorded cassettes but also not replay the cassettes.

Since the git diff is also being changed to only look at a single file isn't this change not needed.

**Comment by shrik450** [comment]
> My understanding is changing the flag on pytest makes this not change the recorded cassettes but also not replay the cassettes.

Yes, this is expected. The scheduled CI run is also meant to test that the cassettes are not out of date in a way that would make the CI pass the test when it should fail, e.g. if the response format changes and something breaks in py-allspice.

**Comment by McRaeAlex** [comment]
Can you write a comment above the pytest command explaining that.

```
We disable the cassette for the scheduled run in order to verify that the CI is not passing due to cached responses (when it should fail).
```

**Review by McRaeAlex — APPROVED** [review]

**Review by kdumontnu — APPROVED** [review]
Should we document & periodically rewrite the cassettes? Maybe on a cron schedule?

Are there not some cases where headers & changes to server response will affect py-allspice code? What about a route that no longer exists or accepts a parameter?

**Comment by shrik450** [comment]
> Should we document & periodically rewrite the cassettes? Maybe on a cron schedule?

This is best handled by us doing this manually when we see a build failure, because we want to check the changes and verify that they're not unexpected, like:

> Are there not some cases where headers & changes to server response will affect py-allspice code? What about a route that no longer exists or accepts a parameter?

😁

**Comment by kdumontnu** [comment]
> > Should we document & periodically rewrite the cassettes? Maybe on a cron schedule?
> 
> This is best handled by us doing this manually when we see a build failure, because we want to check the changes and verify that they're not unexpected, like:

Can you add that note to the "Test" section in the Readme with `python -m pytest --record-mode=rewrite` command?

**Comment by shrik450** [comment]
> Can you add that note to the "Test" section in the Readme with `python -m pytest --record-mode=rewrite` command?

Added 👍

**Pull request merged**
