### PR TITLE
Add endpoints for repo topics and repo search

### PR DESCRIPTION
**Pull request by shrik450**
Also add an example script for cloning all repos with a topic.

### CODE REVIEW

**Comment by danielallspice** [comment]
I don't want to hold up this merge, but it would be nice to have an example that parses a file and adds topics based on the file. It's a two part process, 
1) script adding topics
2) script cloning all repos with topic

I don't know yml very well but something like
```
Topic_to_add:
  - org
   - reponame1
   - reponame2
```

**Review by danielallspice — APPROVED** [review]

**Comment by McRaeAlex** [comment]
I don't know what our overall thoughts are as a company for scripts like these. 

While I understand this was for a particular customer I can't imagine many we plan on continuing to write scripts and examples for every possible workflow / company. I think we should consider pushing customers to look at our API documentation page in the future and allowing them to create the scripts themselves. 

For example from the script included I think it is reasonable to expect a customer to be able to modify it such that it only clones repos from a single topic. For the script adding topics I would expect we point them to API documentation and associated python functionality rather than write it for them.

**Review by McRaeAlex — APPROVED** [review]
Question: do we generate documentation which we could include in pypi?

**Comment by shrik450** [comment]
No, we don't have docs like you would have on docs.rs for py-allspice. There's an open issue for it: #9

**Comment by danielallspice** [comment]
> 
We do push back on customers and point them to the API.
In this case, pulling all the repos from topics is only 1/2 a solution. Customers also need a way to populate the topics. Manually populating the repos is out of the question for customers with hundreds of repos.

**Comment by shrik450** [comment]
Added the add script as well. The yaml format is a little different as the topic: owner: name format gets very bulky in shorter cases, and is harder to read in longer cases.

**Review by danielallspice — APPROVED** [review]

**Pull request merged**
