### PR TITLE
Prep for 3.0 release

### PR DESCRIPTION
**Pull request by shrik450**
Updates the changelog and bumps the version number in setup.py.

### CODE REVIEW

**Comment by danielallspice** [comment]
@shrik450 is there a way to get the version of AllSpice? What would be the best way to integrate that into an action? Should we check to see if py-allSpice is v3 or greater?

**Review by danielallspice — APPROVED** [review]
lgtm

**Comment by shrik450** [comment]
> @shrik450 is there a way to get the version of AllSpice? What would be the best way to integrate that into an action? Should we check to see if py-allSpice is v3 or greater?

There isn't one directly within the library, and we should probably add a `__version__` value to the module. But if you need a solution ASAP, you can use the method in this SO answer: https://stackoverflow.com/a/56331414

**Review by kdumontnu — CHANGES_REQUESTED** [review]
I think we forgot to update the [Readme](https://github.com/AllSpiceIO/py-allspice/tree/main/examples/generate_bom#bom-generation) when we added variants in #86 

Otherwise 👍

**Comment by shrik450** [comment]
Thanks for catching that, updated 👍

**Review by kdumontnu — APPROVED** [review]
👍

**Pull request merged**
